### ISSUE TITLE
Logging starting/stopping not working properly

### ISSUE THREAD

**Issue by SchmidtKrisztian** [omnt/OpenMobileNetworkToolkit#17]
Hi,

I am very interested in this project and testing the software on private and public 5G networks. At the begining I only tested it with logging in a local file without the carrier privilage. I am using the app on a Samsung galaxy S22. For some reason i have some trouble with starting and stopping the logging service.

I enabled the "Log in file" option and set it to 1000 ms, named the measurement and set the tag to device=YourDevice. I picked the network information signal data and Ip address options.

As soon as I want to start the Logging, it does not want to start until I close and reopen the app. After i am done with my measuremant I wasnt able to stop the logging with turning the enable switch off, the app keeps logging. I managed to make it stop with crashing the app. I discovered that if I want to change the access network type to anything but NGRAN the app crashes no matter if I am connected to 3G/4G/5G.

The debug logs are the following:

java.lang.SecurityException: setNetworkSelectionModeManual
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
	at android.os.Parcel.createException(Parcel.java:3053)
	at android.os.Parcel.readException(Parcel.java:3036)
	at android.os.Parcel.readException(Parcel.java:2978)
	at com.android.internal.telephony.ITelephony$Stub$Proxy.setNetworkSelectionModeManual(ITelephony.java:10504)
	at android.telephony.TelephonyManager.setNetworkSelectionModeManual(TelephonyManager.java:10460)
	at android.telephony.TelephonyManager.setNetworkSelectionModeManual(TelephonyManager.java:10401)
	at de.fraunhofer.fokus.OpenMobileNetworkToolkit.SettingPreferences.MobileNetworkSettingsFragment.-$$Nest$mhandleSetNetwork(Unknown Source:177)
	at retrofit2.OkHttpCall$1.onPreferenceChange(Unknown Source:50)
	at androidx.preference.Preference.callChangeListener(Unknown Source:4)
	at androidx.preference.DropDownPreference$1.onItemSelected(Unknown Source:43)
	at android.widget.AdapterView.fireOnSelected(AdapterView.java:1398)
	at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:1387)
	at android.widget.AdapterView.-$$Nest$mdispatchOnItemSelected(Unknown Source:0)
	at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:1345)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

Can I get some help with that issue, if I am doing something wrong.

**Comment by hajoha** [comment]
Hi,
sorry for the delay in getting back to you. 
It sounds like you're having two issues:
1. Logging isn't working
2. You need to change the Access Network Type

Which app version are you using?
For the first issue, I'm not able to reproduce it with the latest version. If you could provide the logcat, that would be helpful.
For the second issue, you need Carrier Permissions. However, the app shouldn't crash, and I'll fix that. Thanks for the heads-up!

**Comment by SchmidtKrisztian** [comment]
Hi,

Thank you for you reply, I just updated the software and now it works fine now.
I do not have CARRIER privilages so thats why it crashes probably.

I also maneged to crash te software by giveing the wrong parameters, during setting up the remove influxdb access. When I wrote the bucket name instead of the bucket ID the app crashed and i could not reopen until i deleted every app data. But i figured it out. 

An other suggestion i can give, it would be nice if i could force stop an iperf3 test, sometimes it stucks. An if I want to create a heatmap of a bigger area, the most convinient way to start an iperf3 test is to start it with -t 0. If I do so it goes until i close it manually, but I did not find a way to close it in the app.

Thank you so much for you help, the project is very intresting for me. I will coninue testing it on different environment and try to give as much feedback as I can.

**Comment by hajoha** [comment]
>Thank you for you reply, I just updated the software and now it works fine now.
I do not have CARRIER privilages so thats why it crashes probably.

At any point, the app should not crash.

> I also maneged to crash te software by giveing the wrong parameters, during setting up the remove influxdb access. When I wrote the bucket name instead of the bucket ID the app crashed and i could not reopen until i deleted every app data. But i figured it out.

The app should work with either the Bucket-ID or Bucket-Name; we have successfully tested both. Maybe there was an extra space?

> An other suggestion i can give, it would be nice if i could force stop an iperf3 test, sometimes it stucks. An if I want to create a heatmap of a bigger area, the most convinient way to start an iperf3 test is to start it with -t 0. If I do so it goes until i close it manually, but I did not find a way to close it in the app.

There is a way to do this: you can swipe on the Instance overview to the right and click on stop. I will update the doc asap.

> Thank you so much for you help, the project is very intresting for me. I will coninue testing it on different environment and try to give as much feedback as I can.

Thank you, feedback is always welcome!
