### ISSUE TITLE
[BUG] - iPerf3 test not running

### ISSUE THREAD

**Issue by bojanlungulov** [omnt/OpenMobileNetworkToolkit#34]
### Context
- **Device:** Samsung Galaxy s22
- **Carrier Privileges (Y/N):**
- **Android Version:** 14
- **App Version:** 0.3
- **Git Hash:** 0b9b316

### Description
When iPerf3 test is started it just keeps running but doesn't show any output, no data are displayed about the test result. 

### How to Reproduce
1. Go to 'iPerf3
2. Enter server address and port
3. Start the test
4. Open instances 
5. Test is only running without results displayed. 

### Expected Behavior
When iPerf3 test started it should show test results in the output screen. 

### Actual Behavior
Test just keep running without any results displayed. 

### Screenshots
![001_start](https://github.com/user-attachments/assets/7fc81dbd-41f9-4c58-901b-e4d601ffe1bd)
![002_result](https://github.com/user-attachments/assets/ea46b699-c18b-4e5f-857d-55765f43d6b1)

### Additional Context
After checking logcat there is an error that library is missing. So the question is how to build the application so that required iPerf3 library is included in APK file. 

Installed iPerf3 on my PC, and run the test with the same parameters and it was successful, so server should be available and working. 

`Work [ id=dba034fe-132f-4ac8-9bb2-76f753564beb, tags={ de.fraunhofer.fokus.OpenMobileNetworkToolkit.Iperf3.Iperf3Worker, iperf3Run, 79f931b4-cad7-4548-adc8-535c50e31a43 } ] failed because it threw an exception/error
                                                                                                    java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: No implementation found for int de.fraunhofer.fokus.OpenMobileNetworkToolkit.Iperf3.Iperf3Worker.iperf3Wrapper(java.lang.String[], java.lang.String) (tried Java_de_fraunhofer_fokus_OpenMobileNetworkToolkit_Iperf3_Iperf3Worker_iperf3Wrapper and Java_de_fraunhofer_fokus_OpenMobileNetworkToolkit_Iperf3_Iperf3Worker_iperf3Wrapper___3Ljava_lang_String_2Ljava_lang_String_2) - is the library loaded, e.g. System.loadLibrary?
                                                                                                    	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:515)
                                                                                                    	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:474)
                                                                                                    	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:316)
                                                                                                    	at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: java.lang.UnsatisfiedLinkError: No implementation found for int de.fraunhofer.fokus.OpenMobileNetworkToolkit.Iperf3.Iperf3Worker.iperf3Wrapper(java.lang.String[], java.lang.String) (tried Java_de_fraunhofer_fokus_OpenMobileNetworkToolkit_Iperf3_Iperf3Worker_iperf3Wrapper and Java_de_fraunhofer_fokus_OpenMobileNetworkToolkit_Iperf3_Iperf3Worker_iperf3Wrapper___3Ljava_lang_String_2Ljava_lang_String_2) - is the library loaded, e.g. System.loadLibrary?
                                                                                                    	at de.fraunhofer.fokus.OpenMobileNetworkToolkit.Iperf3.Iperf3Worker.iperf3Wrapper(Native Method)
                                                                                                    	at de.fraunhofer.fokus.OpenMobileNetworkToolkit.Iperf3.Iperf3Worker.doWork(Iperf3Worker.java:108)
                                                                                                    	at androidx.work.Worker$1.run(Worker.java:82)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
                                                                                                    	at java.lang.Thread.run(Thread.java:1012) 
`

**Comment by hajoha** [comment]
Hi,

Please add the .so files to the app by following this [link](https://github.com/omnt/iperf). Alternatively, you can build them from source or download the latest artifacts from the Release page.

Best regards,

**Comment by hajoha** [comment]
Hi RkShaRkz,

This doesn’t seem to be an issue with the app itself. Could you check the contents of the log file `iperf3_2024-11-01_13_47_24.702_d0204635-6c91-41b0-9936-fff03c57fa72.json`?

When I run the test on my computer, I receive the following:

```
foo@bar:$ iperf3 -c ping.online.net -p 5201 -t 20 --json-stream --connect-timeout 500
{"event":"error","data":"the server is busy running a test. try again later"}
{"event":"end","data":{}}
```

And on the Android app, I get this:
![image](https://github.com/user-attachments/assets/84f36100-01bd-40fc-aa44-0cd7ae5dc686)

The iPerf3 server is currently busy with another test, and the client returns a code of 1 as expected. If possible, try deploying your own iPerf3 server or using a different one.

**Comment by RkShaRkz** [comment]
> nChang

Indeed, it was most likely not a problem with the app at all. I might have just had internet off. I'm getting the following results now

![image](https://github.com/user-attachments/assets/8d0faf2a-1367-4a01-bc6f-2116d577ba07)

![image](https://github.com/user-attachments/assets/efb54411-fcf4-43f7-b91c-54233bbce3fe)

and i guess that (the double checkmarks) means it's working fine?

**Comment by hajoha** [comment]
Please read the [Doc](https://github.com/omnt/OpenMobileNetworkToolkit/blob/main/docs/iperf3.md).
